import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { ReactQueryProvider } from "../components/ui/react-query-provider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ReactQueryProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <header
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                padding: "1rem 2rem",
                borderBottom: "1px solid #eee",
              }}
            >
              <span
                style={{
                  fontWeight: 700,
                  fontSize: "1.5rem",
                  letterSpacing: "0.05em",
                }}
              >
                Chari-ty
              </span>
              <nav
                style={{ display: "flex", gap: "1rem", alignItems: "center" }}
              >
                <SignedIn>
                  <Link
                    href="/dashboard"
                    style={{
                      padding: "0.5rem 1rem",
                      borderRadius: 6,
                      textDecoration: "none",
                      color: "inherit",
                    }}
                  >
                    Dashboard
                  </Link>
                </SignedIn>
                <SignedOut>
                  <SignInButton forceRedirectUrl="/dashboard">
                    <button
                      style={{
                        padding: "0.5rem 1rem",
                        borderRadius: 6,
                        border: "1px solid #ccc",
                        background: "#fff",
                        cursor: "pointer",
                      }}
                    >
                      Sign In
                    </button>
                  </SignInButton>
                  <SignUpButton forceRedirectUrl="/dashboard">
                    <button
                      style={{
                        padding: "0.5rem 1rem",
                        borderRadius: 6,
                        border: "1px solid #ccc",
                        background: "#fff",
                        cursor: "pointer",
                      }}
                    >
                      Sign Up
                    </button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <UserButton afterSignOutUrl="/" />
                </SignedIn>
              </nav>
            </header>
            {children}
          </body>
        </html>
      </ReactQueryProvider>
    </ClerkProvider>
  );
}
